### ISSUE TITLE
Using custom pages as custom homepages

### ISSUE THREAD

**Issue by mrgame64** [psychobunny/nodebb-plugin-custom-pages#14]
The idea is to make all the custom pages available to choose as homepage routes in "ACP/General/Home Page".

I'm planning to implement this feature as long as it's something that the community needs and/or desires. Let me know what you think!

**Comment by psychobunny** [comment]
Go for it:) looking forward to it. Thanks!

**Comment by pitaj** [comment]
This is already in `nodebb-plugin-custom-homepage`

**Comment by mrgame64** [comment]
@pitaj Exactly. The purpose is to give the homepage functionality to this plugin
