### ISSUE TITLE
Seems to doesn't work after "Reload Forum" on NodeBB v0.9.x 

### ISSUE THREAD

**Issue by agusputra** [psychobunny/nodebb-plugin-custom-pages#25]
If I reload NodeBB using top right menu "Reload Forum", then this plugin seems doesn't work, result route not found. But It work well after forum restarted.

**Comment by paviro** [comment]
For me it does not work at all even when restarting. Always `route not found`.

**Comment by mralexgray** [comment]
I can confirm on latest weekly this bug still exists,,  full restart is required..  @psychobunny , any ETA on a fix?  need help with it?

**Comment by psychobunny** [comment]
Thanks for the offer, would appreciate it - been busy sorry guys!

I confirm that this is broken on latest. Last week I had installed it for a client but had to revert to the previous minor semver version and it worked.

So as a stop gap, install the older version and you should be good.

**Comment by psychobunny** [comment]
The version confirmed working on my end is 0.2.4

Btw, this plugin is open for takeover if anybody is dedicated enough to want to take care of it :)

**Comment by psychobunny** [comment]
@julianlam - the newer commits were from your end - I recall some issue with hotswap route being undefined, any idea?

**Comment by julianlam** [comment]
I'll take a look.

**Comment by mralexgray** [comment]
@psychobunny i tried `0.2.4` but still have to restart.  any tips?  if i want to take a stab at fixing it, where should i start?

**Comment by julianlam** [comment]
This plugin doesn't require reloading of the forum, by the way.

**Comment by julianlam** [comment]
Ignore the commit/PR above, but this should be fixed if you update to latest NodeBB: https://github.com/NodeBB/NodeBB/commit/34cafbc0a80d5ca4e66a1720607c4fba2b02a576
