### ISSUE TITLE
delete page doesnt delete item

### ISSUE THREAD

**Issue by chrismccoy** [psychobunny/nodebb-plugin-custom-pages#36]
even after removing the page from the settings, and the route no longer exists in the navigation, its still showing up. even restarted the nodebb.

**Comment by mralexgray** [comment]
there are DEFINITELY deletion issues...


a la
`Error: EBUSY: resource busy or locked, unlink blah blah blah`

**Comment by psychobunny** [comment]
Sorry for the late reply here. I can't reproduce this on the latest version of the plugin though, I get a "Not Found" error
