### ISSUE TITLE
Pages does not get deleted on restart when using master branch

### ISSUE THREAD

**Issue by evoixmr** [psychobunny/nodebb-plugin-custom-pages#40]
under \nodebb\public\templates

I have to delete everything, befose I can start using the terminal.

**Comment by G0wd** [comment]
Same problem.

**Comment by Fiiily** [comment]
Starting to regret this upgrade since this plugin breaks the whole website. Ngah

**Comment by Niller2005** [comment]
Disable the plugin.
`./nodebb reset -p nodebb-plugin-custom-pages`
then go to `/nodebb/public/` and do `sudo rm -rf templates/`
you can now start nodebb again

**Comment by Fiiily** [comment]
Wish I knew that before I reinstalled and lost all the avatars. RIP!

**Comment by Faianca** [comment]
So the fix is not to use the Plugin? O.o

**Comment by psychobunny** [comment]
I don't have this issue on the latest version of NodeBB and latest version of this plugin. Possibly has been fixed since then, if you can reproduce it again let me know.... thanks
