### ISSUE TITLE
Question: Is it possible for a page to match multiple/wild card routes?

### ISSUE THREAD

**Issue by QwertyZW** [psychobunny/nodebb-plugin-custom-pages#43]
So under the 'Routes (no spaces)' section of the plugin I would have 'route1/\*'
However currently this seems to match route1/* as it is.

I also tried 'route1,route2' but that also matched it as it is

**Comment by psychobunny** [comment]
Not possible at the moment, and I'm not sure if I'll support this because it makes it a bit more complicated. Sorry!
