### ISSUE TITLE
Incompatibility with NodeBB version 1.5.3

### ISSUE THREAD

**Issue by vinipereira** [psychobunny/nodebb-plugin-custom-pages#46]
This plugin is awesome
but I found it incompatible with version 1.5.3, anyone else?

Thanks!

**Comment by amargon** [comment]
Ah, me too (and I just came here to report an issue and found this one :) ).

So let’s be more specific: in my case, for example, widgets are not being rendered on a custom page. I still have them set up at the ACP, but after upgrade from 1.4.6 to 1.5.3 the custom page is empty.

**Comment by WarbleSync** [comment]
Yeah this is broken for me on 1.5.3 as well.  I did do some testing with the pull requests to fix it but seems like if you put a widget on the page it won't render properly.  I think this has to do with the switch from template.js to benchpressjs

**Comment by Radiergummi** [comment]
Hey @psychobunny I don't want to annoy you with this, but I'm hosting a rather large board in Germany. I'm required by law to provide a page with personal identification information and could be charged as soon as this information is not accessible on the website... It'd be incredible if you'd manage to fix this 😅

**Comment by psychobunny** [comment]
https://github.com/psychobunny/nodebb-plugin-custom-pages/pull/47

seems to do the trick for me, on latest master (which is going to be NodeBB 1.6 pretty soon). I just merged it in and published 0.4.0 😃
