### ISSUE TITLE
Recent Posts have config.relative_path in urls

### ISSUE THREAD

**Issue by agalpin** [psychobunny/nodebb-plugin-custom-pages#52]
When adding Recent Posts widget to custom pages the posts user/read more have invalid urls
e.g. https://xxxx/%7Bconfig.relative_path%7D/post/2

This is with 0.4.1 which is latest under 1.5.3, 1.6.0 randomly crashed so waiting for a few bug fixes.

**Comment by psychobunny** [comment]
Hi, I believe this was an issue with widgets not custom pages: try again with v3.0.6? https://github.com/NodeBB/nodebb-widget-essentials/commits/master
