### ISSUE TITLE
Custom / does not work as it should! Broken SEO path!

### ISSUE THREAD

**Issue by Jenkler** [psychobunny/nodebb-plugin-custom-pages#53]
Make a custom page your landing page / homepage under General -> Homepage and selecting "Custom"

It is impossible to just get www.domain.com to work as custom startpage without /<something>. If I click the logo the path is correct but if i hit enter on www.domain.com url i redirects me to /page-path.

This plugin should have the same function as the old plugin custom homepage that does not work anymore in 1.6.1. Could we add a special path just for the root. Maybe /homepage  that translates to only /

Could you patch this or give me a workaround please. 

Info:
https://community.nodebb.org/topic/11396/custom-homepage-does-not-work-in-1-6-1

**Comment by barisusakli** [comment]
This seems to work now, can you check again.

**Comment by Jenkler** [comment]
Yes, It works fine now ;)

**Comment by psychobunny** [comment]
thanks!
