### ISSUE TITLE
Custom Page Plugin Breaks with v0.7.x

### ISSUE THREAD

**Issue by jdoexyz100** [psychobunny/nodebb-plugin-custom-pages#8]
The custom page plugin seems to break with version 0.7.x. I can create the static page, and navigate to it. However, whenever I place HTML inside the page by going to Extend, Widgets, and then adding in the HTML on my page, the HTML is never generated. It does not show up on the page when navigated to.

**Comment by Radiergummi** [comment]
Same here, but widgets don't work at all on custom pages. No error is thrown on the CLI.

**Comment by camhart** [comment]
Getting this fixed would be mighty helpful :D

I'll see what I can do but I'm just starting with nodebb.  Don't really have tons of time to invest but I need custom pages bad.

**Comment by psychobunny** [comment]
If I don't have this fixed in the next 48 hours, someone ping me here please. 

I wasn't planning to update all of my plugins till post release of 0.7 but since there is some demand here I'll try to look into it tomorrow
