### ISSUE TITLE
Links to custom pages don't finish loading, expects page template

### ISSUE THREAD

**Issue by Radiergummi** [psychobunny/nodebb-plugin-custom-pages#9]
Thank you for the recent update, @psychobunny , custom pages are available again, yay :smile:
But I'm afraid I still have problems. I linked to a newly created page using a relative link (`<a href="/example">example</a>`). When clicked, the loading bar is stuck at 90% and the page won't load. Upon reloading the entire page, the content apears instantly. So this only concerns (relative?) links.  
In Chromes dev console, the following error messages are shown:  

```

nodebb-plugin-custom-pages: loaded
GET https://domain.tld/templates/example.tpl?v=v0.5.0-2-3149-ga5c5295 404 (Not Found)
send @ nodebb.min.js?bbbb573d:3
w.extend.ajax @ nodebb.min.js?bbbb573d:3
ajaxify.loadTemplate @ nodebb.min.js?bbbb573d:15
t.parse @ nodebb.min.js?bbbb573d:14
o @ nodebb.min.js?bbbb573d:15
(anonymous function) @ nodebb.min.js?bbbb573d:14
_.execCb @ nodebb.min.js?bbbb573d:12
x.check @ nodebb.min.js?bbbb573d:12
x.enable @ nodebb.min.js?bbbb573d:12
x.init @ nodebb.min.js?bbbb573d:12
(anonymous function) @ nodebb.min.js?bbbb573d:12

nodebb.min.js?bbbb573d:15 Uncaught Error: Unable to load template: example (Not Found)
$.ajax.error @ nodebb.min.js?bbbb573d:15
u @ nodebb.min.js?bbbb573d:1
f.fireWith @ nodebb.min.js?bbbb573d:1
T @ nodebb.min.js?bbbb573d:3
send.n @ nodebb.min.js?bbbb573d:3

```

**Comment by psychobunny** [comment]
:) Did you try restarting NodeBB?

**Comment by Radiergummi** [comment]
Yup.. I pulled master, updated all plugins and restarted afterwards..

**Comment by psychobunny** [comment]
`example.tpl?v=v0.5.0-2`
This doesn't seem right. You're on the latest master right? dc16a665aec3be17b7b6b01501782ba0a00b0005

**Comment by Radiergummi** [comment]
Just pulled again, I'm on `67eef3653be595225306a7255d338f6bba11d001`.   
Dev console:  
Failed to load https://schreibnacht.de/templates/impressum.tpl?v=v0.5.0-2-3149-ga5c5295 
 resource: the server responded with a status of 404 (Not Found)
nodebb.min.js:15 Uncaught Error: Unable to load template: impressum (Not Found)

**Comment by psychobunny** [comment]
Figured out how to repro. Fixed :)

**Comment by Radiergummi** [comment]
One or two interwebz for you, @psychobunny. You are awesome! :grin:
psychobunny <notifications@github.com> schrieb am Mo., 27. Apr. 2015 um
17:55:

**Comment by psychobunny** [comment]
I only take payment in Over 9000 Internet's, nothing less. 

;)
